apiVersion: v1
kind: Service
metadata:
  name: java-microservices-cicd-service
spec:
  type: ClusterIP
  selector:
    app: java-microservices-cicd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
